name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - jupyterlab=3.0.12
  - seaborn=0.11.1
  - pandas=1.1.4
  - pip=20.3.3
  - pandas-profiling=2.11.0
  - pyarrow=2.0
  - jinja2=3.0.3
  #- wandb=0.12.17
  - pip:
      - wandb==0.12.17